services:
  backend:
    build:
      context: ./backend
    container_name: dreamweaver_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env

  web:
    image: nginx:alpine
    container_name: dreamweaver_frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
